// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzOEXup2DRxawlA1f0ATPSa4-Rgh9L0xs',
    appId: '1:703626794798:web:0bd095a609b3445e050cbf',
    messagingSenderId: '703626794798',
    projectId: 'recycling-point-9b5c1',
    authDomain: 'recycling-point-9b5c1.firebaseapp.com',
    storageBucket: 'recycling-point-9b5c1.firebasestorage.app',
    measurementId: 'G-YDRXRZHRLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzARJpuwW8fV9yFC_-YZRL5AC7VvyuWWs',
    appId: '1:703626794798:android:09cc5aed75ebc8be050cbf',
    messagingSenderId: '703626794798',
    projectId: 'recycling-point-9b5c1',
    storageBucket: 'recycling-point-9b5c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUWb1VaxVfUzNWVnjSO7XULnAMtayDmTM',
    appId: '1:703626794798:ios:58885d1c252cc435050cbf',
    messagingSenderId: '703626794798',
    projectId: 'recycling-point-9b5c1',
    storageBucket: 'recycling-point-9b5c1.firebasestorage.app',
    iosBundleId: 'com.example.recyclingpointMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUWb1VaxVfUzNWVnjSO7XULnAMtayDmTM',
    appId: '1:703626794798:ios:58885d1c252cc435050cbf',
    messagingSenderId: '703626794798',
    projectId: 'recycling-point-9b5c1',
    storageBucket: 'recycling-point-9b5c1.firebasestorage.app',
    iosBundleId: 'com.example.recyclingpointMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzOEXup2DRxawlA1f0ATPSa4-Rgh9L0xs',
    appId: '1:703626794798:web:032c335de5dfb5f3050cbf',
    messagingSenderId: '703626794798',
    projectId: 'recycling-point-9b5c1',
    authDomain: 'recycling-point-9b5c1.firebaseapp.com',
    storageBucket: 'recycling-point-9b5c1.firebasestorage.app',
    measurementId: 'G-CX1CF50KYK',
  );
}
